### ISSUE TITLE
Alternative Product ID for Fingerbot Plus

### ISSUE THREAD

**Issue by shanemeagher** [PlusPlus-ua/ha_tuya_ble#1]
Hi @PlusPlus-ua, many thanks for the integration.

Have been trying it out and I've had to add a new product id (`blliqpsj`) for the 'Adaprox' branded Fingerbot Plus that I have. I did this by duplicating the `yiihr7zh` device.

Here is more info from the regular Tuya integration:
`"name": "Fingerbot Plus",
    "model": "ADFB0301",
    "category": "szjqr",
    "product_id": "blliqpsj",
    "product_name": "Fingerbot Plus",`

Let me know if you need more info.

Edit: I should add that it seems to be working fine with the duplicated details, just changing the product id.

**Comment by PlusPlus-ua** [comment]
Hi,

Thank you so much for response,
I've developed it based only on devices which I own by myself.

Have you an ability to change files on your working HA instance (PC or rpi - despite)? Please change in every file string 'yrnk7mnn' to 'blliqpsj' and restart the HA.

**Comment by PlusPlus-ua** [comment]
Added at version 0.1.1
