### ISSUE TITLE
Error when adding integration

### ISSUE THREAD

**Issue by R00S** [PlusPlus-ua/ha_tuya_ble#104]
"message":"Invalid handler specified"

**Comment by phuse** [comment]
If you are running HA 2024.1 - check this https://github.com/PlusPlus-ua/ha_tuya_ble/issues/98 , manually applying the changes in the files worked for me

**Comment by R00S** [comment]
2024.1.2
Sadly no change for me.
This happens when I try to add the integration from scratch. I did not have tuya BLE before.

**Comment by liouma** [comment]
It works fine for me!
@R00S : are you sure it doesn't work? 
I know it sounds stupid, but could you double check that you removed the - lines and addes all the + lines?
Did you restart HA after?  just after I received the discovery notification, so I did not need to add tuya ble in the integration dashboard.
Hope it help...

**Comment by R00S** [comment]
> It works fine for me! @R00S : are you sure it doesn't work? I know it sounds stupid, but could you double check that you removed the - lines and addes all the + lines? Did you restart HA after? just after I received the discovery notification, so I did not need to add tuya ble in the integration dashboard. Hope it help...

It was something hanging about that stopped me from installing. I dont really know what. I removed tuya, tuya local and local tuya and moved the bluetooth devices to a new tuya account and suddenly it was possible to install. 

Sadly no devices gets detexted...

**Comment by romanad** [comment]
I have same problem

**Comment by ok1vkt** [comment]
I edit files cloud and config flow.... But error is still there :(

**Comment by Moe555** [comment]
Same here...made the changes as described.
Restarted HA and the issue is still there.
HA 2024.2.2
