### ISSUE TITLE
Cant get "ADFB0201 (bnt7wajf)" to work

### ISSUE THREAD

**Issue by urkman5000** [PlusPlus-ua/ha_tuya_ble#11]
hey there went over from the python ble issue chat,

> I've created it https://github.com/PlusPlus-ua/ha_tuya_ble

tried it out, my fingerbot is registered but has no entities or switches to make it action.
mine is listed as "ADFB0201 (bnt7wajf)" and only has a non working signal strength entity which says not available.

App an IOT are setup correctly.

**Comment by PlusPlus-ua** [comment]
Could you please give me information about kind of the fingerbot? Photo of the device will be enough.

**Comment by urkman5000** [comment]
Thx for the reply.
Its this one bought in 2022

________________________________

**Comment by PlusPlus-ua** [comment]
> Its this one bought in 2022

Ok, it looks like you have original fingerbot without sensor button for manual control, I've added device_id to the integration

**Comment by urkman5000** [comment]
Thank you! Will Test it Out when Home again.

________________________________

**Comment by urkman5000** [comment]
Hey there still only the Signal strength entity available when adding the device which is automatically discovered.
using Version 0.1.4


________________________________

**Comment by PlusPlus-ua** [comment]
I haven't yet released a new version, update please sources manually.

**Comment by urkman5000** [comment]
How do i actually update the sources? Already redownloaded it and restarted + reloaded the integration. No success in getting more entities.

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: PlusPlus-ua ***@***.***>
Gesendet: Thursday, May 11, 2023 7:55:51 PM
An: PlusPlus-ua/ha_tuya_ble ***@***.***>
Cc: urkman5000 ***@***.***>; Author ***@***.***>
Betreff: Re: [PlusPlus-ua/ha_tuya_ble] Cant get "ADFB0201 (bnt7wajf)" to work (Issue #11)


I haven't yet released a new version, update please sources manually.

**Comment by Noob25930** [comment]
Hi @PlusPlus-ua Thank you so much for developing this. I tried adding my own product ID for my device manually in the code and it worked. The product id is "5xhbk964".  This is a fingerbot as well. I am new to GitHub so don't know how to contribute directly.

**Comment by urkman5000** [comment]
Hey there, since your new Update came Out it works Like a Charm now. Big Thx!!!

________________________________
