### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Performance20** [PlusPlus-ua/ha_tuya_ble#117]
I installed via HACS in HomeAssistant but if I try to add as new integration, I got always an error like: 

"Error occurred loading flow for integration tuya_ble: cannot import name 'TUYA_SMART_APP' from 'homeassistant.components.tuya.const' (/usr/src/homeassistant/homeassistant/components/tuya/const.py)

I found some hints here with problems with former versions (use last version 2024.02.0). Based on the diff files I change the files by hand but I always get the error.

I there someone who can help me due to provide me a running code version or give me a hint what I have to change on the phyton staff to get it running.

Thx

Helge

**Comment by Performance20** [comment]
problem solved now

**Comment by lamerjack** [comment]
I can't find in HACS, where is my mistake?
