### ISSUE TITLE
Question: Determine if a Fingerbot action actually completed

### ISSUE THREAD

**Issue by gbrooker** [PlusPlus-ua/ha_tuya_ble#124]
Hi, 
Apologies if this is the wrong forum to ask this question - happy to ask elsewhere if there are any suggestions of a better place.

I have implemented my own fingerbot controller (in the Swift language) inspired by many of the open source implementations, including this one (many thanks).

When I send a command to the fingerbot to activate the arm and return it to the top position, I get two responses over bluetooth:
 1. FUN_SENDER_DPS with a single byte of data, which always seems to be zero
 2. FUN_RECEIVE_DP with 4 bytes, -> time & dps = { 101: 1} 

However, sometimes the arm is activated, sometimes not, but I always seem to get the same values in the two responses. I would love to be able to detect if the arm was actually controlled or not. Does anyone else notice the occasional non-activation and know if there is a way to detect whether the device operated or not ?

**Comment by gbrooker** [comment]
I have managed to find a solution. It turns out, and I have't seen this reported elsewhere, Fingetbot status DPs include DP 150 which appears to be a move count. After sending a command to move the arm, wait a couple of seconds for the operation to complete, then send a FUN_SENDER_DEVICE_STATUS command. The count reported in DP 150 will have incremented by 1 for a single movement, or by two for an up/down movement. If the command is ignored (i.e no activation), the count will remain unchanged. Sending the action again seems to encourage the fingerbot to react ! Hope this is of help to someone else one day...

**Comment by tabascoz** [comment]
Hi there Gbrooker, 

How did you managed to get DP150 value in Home Assistant?  Cheers, Tabascoz
