### ISSUE TITLE
Request for another fingerbot model to be added

### ISSUE THREAD

**Issue by semple1990** [PlusPlus-ua/ha_tuya_ble#17]
Looking through the closed issues, I've got the exact same fingerbot as posted in here: https://github.com/PlusPlus-ua/ha_tuya_ble/issues/9

It's connected, but is only showing signal sensor.

Model number is rvdceqjh

I'm also running version 0.1.4

Thanks!

**Comment by semple1990** [comment]
Didn't realise I had closed this. Just for reference I added my model number into the relevant .py files and the integration works fine now. 

Hope this can be added so any future updates don't break my changes. Thanks.

**Comment by PlusPlus-ua** [comment]
Hi, could you please open PR for your changes.
