### ISSUE TITLE
Device is not registered in Tuya cloud?

### ISSUE THREAD

**Issue by theskyisthelimit** [PlusPlus-ua/ha_tuya_ble#19]
that's very cool! This is exactly what I was looking for. I have an Adaprox fingerbot running with the code from redphx with python. it works flawlessly. unfortunately i am not able to get the hacs integration to work. what could be the problem?

![Bildschirmfoto 2023-05-21 um 08 51 18](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/11703464/c31e78ad-bbd6-4e55-b2bc-00feff6a3dde)

I can see the device in the Tuya Cloud. I've had to do this to get the python code running.

![Bildschirmfoto 2023-05-21 um 08 52 03](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/11703464/faf584ad-773a-4bef-ba3a-4d82e57e7618)

**Comment by MrAlucardDante** [comment]
I am facing the same issue.
Device is in the app and on the Tuya Cloud, but I still get the same error message

**Comment by theskyisthelimit** [comment]
@MrAlucardDante what did you add where?

**Comment by MrAlucardDante** [comment]
> @MrAlucardDante what did you add where?

The Adaprox fingetbot plus. It appeared in home assistant, but we I tried to add configure it, I got the same message error as you. I just click submit again and it worked

**Comment by PlusPlus-ua** [comment]
Hi, do you have some logs for your configuration attempt?

**Comment by theskyisthelimit** [comment]
Hello, Unfortunately it's not logging anything. at least I cannot see anything in the home-assistant.log. Should it search somewhere else?

![Bildschirmfoto 2023-05-26 um 17 00 42](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/11703464/fc146f95-197b-4e44-8365-2a87e02902fb)

**Comment by PlusPlus-ua** [comment]
Do you have only one project on Tuya IOT platform?

**Comment by theskyisthelimit** [comment]
yes. Only the one in the first screenshot. sorry to ask, but is a connection to the tuya cloud necessary if I have already extracted the login data with the tool from redphx?

**Comment by PlusPlus-ua** [comment]
I've just decided that it's will be the simplest way for UX. Actually I've taken part of the code from extractor Python script which you have used. It's quite strange. May be Tuya IOT server was temporary down that time. Could you please retry.

**Comment by theskyisthelimit** [comment]
Well. The login seems to work:

`2023-05-26 17:28:30.132 DEBUG (MainThread) [custom_components.tuya_ble.cloud] Successful login for XXXX@gmail.com
2023-05-26 17:28:44.387 DEBUG (MainThread) [custom_components.tuya_ble.cloud] Successful login for XXXX@gmail.com
2023-05-26 17:28:45.354 DEBUG (MainThread) [custom_components.tuya_ble.cloud] Successful login for XXXX@gmail.com
2023-05-26 17:28:46.356 DEBUG (MainThread) [custom_components.tuya_ble.cloud] Successful login for XXXX@gmail.com
`

**Comment by TonsiTT** [comment]
I'm facing the same issue. Although my device is a CubeTouch II

**Comment by TonsiTT** [comment]
the log
`
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/tuya_ble/config_flow.py", line 302, in async_step_device
    credentials = await self._manager.get_device_credentials(
  File "/config/custom_components/tuya_ble/cloud.py", line 263, in get_device_credentials
    await self._fill_cache_item(item)
  File "/config/custom_components/tuya_ble/cloud.py", line 182, in _fill_cache_item
    factory_info = fi_response[TUYA_RESPONSE_RESULT][0]
IndexError: list index out of range
`

**Comment by PlusPlus-ua** [comment]
Try please new version, I've added some additional checks.

**Comment by theskyisthelimit** [comment]
I updated and restarted HA. login still seem to work and the error also still is the same:

2023-06-01 08:15:17.222 DEBUG (MainThread) [custom_components.tuya_ble.cloud] Successful login for XXX@gmail.com
2023-06-01 08:15:20.411 DEBUG (MainThread) [custom_components.tuya_ble.cloud] Successful login for XXX@gmail.com
2023-06-01 08:15:21.420 DEBUG (MainThread) [custom_components.tuya_ble.cloud] Successful login for XXX@gmail.com

**Comment by PlusPlus-ua** [comment]
Are there in log any ERROR lines related to custom_components.tuya_ble.cloud ?

**Comment by theskyisthelimit** [comment]
unfortunately not. everytime i press the "send" button to add the device it writes the log that the login was successfull. nothing else.

**Comment by theskyisthelimit** [comment]
exactly!

**Comment by PlusPlus-ua** [comment]
It must add to log line like this
`2023-06-01 08:03:28.852 DEBUG (MainThread) [custom_components.tuya_ble.cloud] Retrieved: uuid: xxxxxxxxxxxxxxxx, local_key: xxxxxxxxxxxxxxxx, device_id: xxxxxxxxxxxxxxxx, category: wsdcg, product_id: ojzlzzsw, device_name: TYOS温湿度传感器, product_model: , product_name: Temperature&humidity sensor`
for registered devices.

Ensure please that your device present in your project on Tuya IOT site.

**Comment by TonsiTT** [comment]
So my issue got resolved like this.
Instead of going to the integration page and pressing 'Add Integration' and selecting Tuya BLE, I reinstalled the integration and let it stay as is without doing anything. After around 8-10 hours, the Tuya BLE integration found my CubeTouch itself. I then pressed configure on the newly discovered device, and it worked as usual with no error.
Before that, I would always get the "Device is not registered in Tuya cloud" error if I tried to configure manually by going to "Add Integration" and stuff

**Comment by PlusPlus-ua** [comment]
> So my issue got resolved like this.

Is it with new or old version?

**Comment by TonsiTT** [comment]
> > So my issue got resolved like this.
> 
> Is it with new or old version?

The old version

**Comment by TonsiTT** [comment]
I think right now this error is due to the device being found on the cloud but the device not being in the list of devices discovered or connected to home-assistant via bluetooth

**Comment by theskyisthelimit** [comment]
My device shows up automatically as well:

![grafik](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/11703464/a11f9b15-d2ec-4dd5-9ea4-4e4560f4490c)

when I press "Absenden" then the configuration page for tuya login shows up.

<img width="589" alt="grafik" src="https://github.com/PlusPlus-ua/ha_tuya_ble/assets/11703464/b9f10365-f048-4239-b2c5-46c42466c380">

**Comment by TonsiTT** [comment]
> My device shows up automatically as well:
> 
> ![grafik](https://user-images.githubusercontent.com/11703464/242506747-a11f9b15-d2ec-4dd5-9ea4-4e4560f4490c.png)
> 
> when I press "Absenden" then the configuration page for tuya login shows up.
> <img alt="grafik" width="589" src="https://user-images.githubusercontent.com/11703464/242507299-b9f10365-f048-4239-b2c5-46c42466c380.png">

Does it show automatically on the integration page like this?
![image](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/50301560/d4447fb2-8427-4b1f-a407-04d543c4d60e)

**Comment by theskyisthelimit** [comment]
Yes. Sorry, I uploaded the wrong screenshot. I updated it. When I press "configure" then I have to add all the informations.

**Comment by theskyisthelimit** [comment]
Tonight, I will try and remove the fingerbot from the tuya cloud and re-add it. maybe it helps

**Comment by TonsiTT** [comment]
> My device shows up automatically as well:
> <img alt="grafik" width="302" src="https://user-images.githubusercontent.com/11703464/242507627-0189f3b2-1d06-438e-9781-8fe6d4e8822d.png">
> 
> when I press "Absenden" then the configuration page for tuya login shows up.
> <img alt="grafik" width="589" src="https://user-images.githubusercontent.com/11703464/242507299-b9f10365-f048-4239-b2c5-46c42466c380.png">

The only difference in my case was I had the official Tuya integration installed as well with the credentials added.

An offshoot suggestion, but could you install that, configure it with the credentials and then reboot home-assistant.
Once rebooted, wait for the device to show up again and configure it

**Comment by theskyisthelimit** [comment]
good suggestion! I added the official tuya and put in all my login informations. after that, this "configuration" page for "Tuya BLE" was not showing up again. So I guess tuya ble takes the login informations from the official tuya intergration. good! But the error stays the same. I will try to re-add the project and device in the tuya cloud. wish me luck.

**Comment by Zylazy** [comment]
I have the same issue. I am trying to add my temp&humidity sensor (Product Category: wsdcg), but I always get this error: "Device is not registered in Tuya cloud"
I have removed via my mobile app, and added again, but it did not help.

**Comment by PlusPlus-ua** [comment]
> I have the same issue. I am trying to add my temp&humidity sensor (Product Category: wsdcg), but I always get this error: "Device is not registered in Tuya cloud" I have removed via my mobile app, and added again, but it did not help.

Do you have any logs?

**Comment by theskyisthelimit** [comment]
Sorry for the long delay. I was away from home. 
I actually just tried to add the device again and it worked somehow. I didn't change anything in the tuya cloud.
