### ISSUE TITLE
"Invalid flow specified" for CubeTouch II

### ISSUE THREAD

**Issue by AlbertORoura** [PlusPlus-ua/ha_tuya_ble#27]
![image](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/34156077/212837f7-9692-4bcf-801d-2cb2857bf3ee)

Please, I need help to integrate my cubetouch II to my home assistant. I have other tuya devices already integrated with no problem but I am getting this error message for this new device.

Any advice? Any clue what might be going wrong?

Thank you so much.

**Comment by PlusPlus-ua** [comment]
Hi, are there any errors in the log?

**Comment by AlbertORoura** [comment]
I have filtered for BLE in the logs and there are no error messages in the last week.

**Comment by PlusPlus-ua** [comment]
Could you please check if on your HA server /config/custom_components/tuya_ble/strings.json and /config/custom_components/tuya_ble/translations/en.json exists and are unchanged?

Such error could occur if flow manager unable to find some info by step_id, first suspected is strings.

**Comment by AlbertORoura** [comment]
Hello @PlusPlus-ua ,

Indeed the two files exists and are unchanged.

Could it be a connectivity problem?

Perhaps by the time I launch the setup process, the device is in sleep mode and is not responding.

**Comment by PlusPlus-ua** [comment]
No, It couldn't be a connectivity problem.

Full log may help to find a root of the problem. It looks like some inconsistent between HA core and integration.

**Comment by AlbertORoura** [comment]
Solved. It was a bluetooth cut when I'm trying to configurate the device.

Now I'm stuck because the configuration needs to see online the device and it is offline
![image](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/34156077/fc9b3e70-c3b7-427b-a670-94ce5b05e06c)

Any tips?

**Comment by AlbertORoura** [comment]
Solved. It was a bluetooth cut when I'm trying to configurate the device.

but when I'm finishing the configuration it seems that the device it's not found (another bluetooth cut?):
![image](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/34156077/098163c8-3946-41d8-9bf2-0a64f2ee5b48)

**Comment by AlbertORoura** [comment]
Indeed, was a bluetooth problem. I solved using an ESP32 bluetooth bridge.

Thanks for your time and your help @PlusPlus-ua
