### ISSUE TITLE
Login error (2401): username or password wrong

### ISSUE THREAD

**Issue by RmG152** [PlusPlus-ua/ha_tuya_ble#35]
Hello,

I get the following error when configuring the application:
Login error (2401): username or password wrong

I am using the "Smart Life" credentials with the same country as the app.

I tried changing the password and it doesn't work either.

I have other tuya devices integrated from the official integration.

**Comment by catduckgnaf** [comment]
I am having the same issue. I tried the same credentials I am using with Tuya Local, what am I missing here?

**Comment by PlusPlus-ua** [comment]
Hi, provide please debug logs of the problem. In order to enable debug log for the integration, just add next lines to your configuration.yaml file:

```
logger:
  default: info
  logs:
    custom_components.tuya_ble: debug

```

**Comment by RmG152** [comment]
Hello,

Sorry for replying so late, I didn't get anything in the logs, but I managed to solve the problem.

For this I followed the official documentation of the Tuya integration, specifically this section: [2406: skill id invalid](https://www.home-assistant.io/integrations/tuya/#2406-skill-id-invalid)

Maybe it would be nice to add this information somehow in the integration documentation.

**Comment by StaRipper** [comment]
Tis solve it:

https://community.home-assistant.io/t/tuya-integration-error-2406-skill-id-invalid/372831/16
