### ISSUE TITLE
Request for Moes R2 smart lock (Tuya)

### ISSUE THREAD

**Issue by Sairon92** [PlusPlus-ua/ha_tuya_ble#50]
Hi. Thanks for your work.
Could you please add a Tuya R2 smart lock ( https://moeshouse.com/products/eu-version-bluetooth-smart-door-lock-bank-grade-aes128-bit-and-tls-encryption-keypad-bundle-bluetooth-sensor-unlocking-tuya-smart-app-remote-unlocking )
 "category": "jtmspro",
 "model": "BDL-BG-2-US",
 "name": "R2 Smart Lock",
 "product_id": "s6amdvmm",
 "product_name": "ZC-BG 美式改装门锁R2"

**Comment by Sairon92** [comment]
Standart instruction set:
{
  "result": {
    "category": "jtmspro",
    "functions": [
      {
        "code": "unlock_method_create",
        "desc": "unlock method create",
        "name": "unlock method create",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "unlock_method_delete",
        "desc": "unlock method delete",
        "name": "unlock method delete",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "unlock_method_modify",
        "desc": "unlock method modify",
        "name": "unlock method modify",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "lock_record",
        "desc": "lock record",
        "name": "lock record",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "beep_volume",
        "desc": "beep volume",
        "name": "beep volume",
        "type": "Enum",
        "values": "{\"range\":[\"mute\",\"normal\"]}"
      },
      {
        "code": "automatic_lock",
        "desc": "automatic lock",
        "name": "automatic lock",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "auto_lock_time",
        "desc": "auto lock time",
        "name": "auto lock time",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1,\"max\":1800,\"scale\":0,\"step\":1}"
      },
      {
        "code": "rtc_lock",
        "desc": "rtc lock",
        "name": "rtc lock",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "manual_lock",
        "desc": "manual lock",
        "name": "manual lock",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "synch_method",
        "desc": "synch method",
        "name": "synch method",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "guide_page_act",
        "desc": "guide page act",
        "name": "guide page act",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "remote_no_dp_key",
        "desc": "remote no dp key",
        "name": "remote no dp key",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "record",
        "desc": "record",
        "name": "record",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "check_code_set",
        "desc": "check code set",
        "name": "check code set",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "ble_unlock_check",
        "desc": "ble unlock check",
        "name": "ble unlock check",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "remote_pd_setkey_check",
        "desc": "remote pd setkey check",
        "name": "remote pd setkey check",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "special_control",
        "desc": "special control",
        "name": "special control",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "unlock_ble_ibeacon",
        "desc": "unlock ble ibeacon",
        "name": "unlock ble ibeacon",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "ibeacon_scan_mode",
        "desc": "ibeacon scan mode",
        "name": "ibeacon scan mode",
        "type": "Enum",
        "values": "{\"range\":[\"always\",\"5min\",\"10min\",\"20min\",\"40min\",\"60min\",\"90min\",\"120min\"]}"
      },
      {
        "code": "rssi_sensitivity_level",
        "desc": "rssi sensitivity level",
        "name": "rssi sensitivity level",
        "type": "Enum",
        "values": "{\"range\":[\"inactive\",\"90db\",\"80db\",\"70db\",\"60db\",\"50db\",\"40db\",\"30db\",\"20db\"]}"
      },
      {
        "code": "autolock_delay_level",
        "desc": "autolock delay level",
        "name": "autolock delay level",
        "type": "Enum",
        "values": "{\"range\":[\"inactive\",\"4s\",\"6s\",\"8s\",\"10s\",\"12s\"]}"
      },
      {
        "code": "ibeacon_switch",
        "desc": "ibeacon switch",
        "name": "ibeacon switch",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },

**Comment by leolebtag** [comment]
Hi darki73,

I will try to help you. To add the smart lock, here's what I did:

First, I set up an ESP32 Bluetooth proxy near the smart lock. I then unbound the smart lock from the Bluetooth gateway, removed the smart lock battery, counted to 10, and then reinserted it. After this, my smart lock was immediately discovered by Home Assistant, and I was able to add the device.

You can try this method to check if your device is compatible. If your device doesn't appear or can't be added, I suspect it could be using a different version of BLE, one that's not implemented in this add-on.

Please note that even if your device is added after this procedure, it won't be ready to work immediately. The extension doesn't have the configuration for this particular device. We will need to add support for this specific smart lock.

**Comment by alexxx113** [comment]
https://github.com/alexxx113/ha_tuya_ble/tree/main
It seems to work...

**Comment by Sairon92** [comment]
@alexxx113
Hi Alex, Thank you for your job.
I try to setup my lock with your file
I can add the lock, with 24 entities
I use esp32 bluetooth proxy. Set it near the lock (1m).
But all of this entities is unavailable.
![image](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/75335111/3bd0cada-bd2b-4637-a268-6f578fe78486)

and get this error:
![image](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/75335111/ff144a20-ea73-4d55-8d6f-4523affc4d42)
![image](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/75335111/6b95df30-bb85-46c1-a90f-09baa87d340d)


Logger: custom_components.tuya_ble.tuya_ble.tuya_ble
Source: custom_components/tuya_ble/tuya_ble/tuya_ble.py:503
Integration: Tuya BLE
First occurred: 12:58:14 PM (7 occurrences)
Last logged: 1:04:28 PM

DC:23:4D:8E:7B:2C: Device unexpectedly disconnected; RSSI: -73
DC:23:4D:8E:7B:2C: Device unexpectedly disconnected; RSSI: -74
DC:23:4D:8E:7B:2C: Device unexpectedly disconnected; RSSI: -72

Logger: custom_components.tuya_ble.tuya_ble.tuya_ble
Source: custom_components/tuya_ble/tuya_ble/tuya_ble.py:294
Integration: Tuya BLE
First occurred: 12:58:45 PM (12 occurrences)
Last logged: 1:03:56 PM

DC:23:4D:8E:7B:2C: timeout receiving response, RSSI: -74
DC:23:4D:8E:7B:2C: Sending device info request failed
DC:23:4D:8E:7B:2C: timeout receiving response, RSSI: -73
DC:23:4D:8E:7B:2C: timeout receiving response, RSSI: -72

Logger: homeassistant.components.number
Source: helpers/entity_platform.py:613
Integration: Number (documentation, issues)
First occurred: 12:57:40 PM (1 occurrences)
Last logged: 12:57:40 PM

Platform tuya_ble does not generate unique IDs. ID bfab57vjl86zi3jm-unlock_phone_remote is already used by number.bfab57vjl86zi3jm_unlock_phone_remote - ignoring sensor.bfab57vjl86zi3jm_unlock_phone_remote

**Comment by Sairon92** [comment]
2023-08-26 12:21:01.201 WARNING (MainThread) [custom_components.tuya_ble.tuya_ble.tuya_ble] DC:23:4D:8E:7B:2C: Device unexpectedly disconnected; RSSI: -74
2023-08-26 12:21:31.245 ERROR (MainThread) [custom_components.tuya_ble.tuya_ble.tuya_ble] DC:23:4D:8E:7B:2C: timeout receiving response, RSSI: -73
2023-08-26 12:21:31.246 ERROR (MainThread) [custom_components.tuya_ble.tuya_ble.tuya_ble] DC:23:4D:8E:7B:2C: Sending device info request failed
2023-08-26 12:21:31.247 DEBUG (MainThread) [custom_components.tuya_ble.tuya_ble.tuya_ble] DC:23:4D:8E:7B:2C: Connecting; RSSI: -73
2023-08-26 12:21:41.283 DEBUG (MainThread) [custom_components.tuya_ble.tuya_ble.tuya_ble] DC:23:4D:8E:7B:2C: Connected; RSSI: -73
2023-08-26 12:21:41.341 DEBUG (MainThread) [custom_components.tuya_ble.tuya_ble.tuya_ble] DC:23:4D:8E:7B:2C: Sending device info request
2023-08-26 12:21:41.341 DEBUG (MainThread) [custom_components.tuya_ble.tuya_ble.tuya_ble] DC:23:4D:8E:7B:2C: Sending packet: #24 FUN_SENDER_DEVICE_INFO
2023-08-26 12:22:11.233 WARNING (MainThread) [custom_components.tuya_ble.tuya_ble.tuya_ble] DC:23:4D:8E:7B:2C: Device unexpectedly disconnected; RSSI: -73
2023-08-26 12:22:41.343 ERROR (MainThread) [custom_components.tuya_ble.tuya_ble.tuya_ble] DC:23:4D:8E:7B:2C: timeout receiving response, RSSI: -71
2023-08-26 12:22:41.344 ERROR (MainThread) [custom_components.tuya_ble.tuya_ble.tuya_ble] DC:23:4D:8E:7B:2C: Sending device info request failed
2023-08-26 12:22:41.345 DEBUG (MainThread) [custom_components.tuya_ble.tuya_ble.tuya_ble] DC:23:4D:8E:7B:2C: Connecting; RSSI: -71
2023-08-26 12:22:42.474 DEBUG (MainThread) [custom_components.tuya_ble.tuya_ble.tuya_ble] DC:23:4D:8E:7B:2C: Connected; RSSI: -71
2023-08-26 12:22:42.512 DEBUG (MainThread) [custom_components.tuya_ble.tuya_ble.tuya_ble] DC:23:4D:8E:7B:2C: Sending device info request
2023-08-26 12:22:42.512 DEBUG (MainThread) [custom_components.tuya_ble.tuya_ble.tuya_ble] DC:23:4D:8E:7B:2C: Sending packet: #25 FUN_SENDER_DEVICE_INFO

**Comment by alexxx113** [comment]
Connect lock app android or ios, not gateway!
Remove lock geteway!
Or delete device app and gateway
Disconect power gateway!
And new connect in app
Turn off bluetooth in device
Add in home assistant.
Reconect battery

esp32 bluetooth proxy  no test....

**Comment by Sairon92** [comment]
@alexxx113 , Thank you. Everything is working!

**Comment by Sairon92** [comment]
@alexxx113  , Thank you. Everything is working!
