### ISSUE TITLE
No configured devices found

### ISSUE THREAD

**Issue by andypnz** [PlusPlus-ua/ha_tuya_ble#6]
Got this working on a test HA installation. Now moving to my main install....

Followed the same steps as previous, but now get this:

![image](https://user-images.githubusercontent.com/11356342/234811236-48298773-ec6c-465f-b5c2-0a1e674b755e.png)

Is there something special to 'removed' a configured device from an old installation?

Any thoughts?

**Comment by PlusPlus-ua** [comment]
I have answered you on the forum, so I close this issue
