### ISSUE TITLE
Not working since update to 2023.11.0?

### ISSUE THREAD

**Issue by igalg99** [PlusPlus-ua/ha_tuya_ble#82]
EDIT: 
The problem was discharged device (s) . NOT the integration.  It appears that all the 3 of  the  CubeTouch devices ran out of battery at the same time right after updating to HA 2023.11. talking about co-incidence. after charging the devices all works 

Is any one else experience problem with the integration after update to 2023.11?
Also updated  esphome to 2023.10.6. At the same time
All worked well but now integration is not loaded. 

Haven't tried yet to revert the updates but I am assuming it would fix the issue. 

Anyone else has issues since latest update ?

Update: 
seems that the issue is specifically with CubeTouch II -  CBTB3002 (xhf790if). I have 3 of those and none of them load
I have also 1 Fingerbot ADFB0301 (yiihr7zh) - this one still works properly.

**Comment by cloudbr34k84** [comment]
I dont think this is being maintained anymore

**Comment by igalg99** [comment]
Oh that's a pity. Are there some other repos of forks that integrate tuya
ble devices ?

**Comment by igalg99** [comment]
@PlusPlus-ua sorry to bother but I tag you since you the creator of this integration/repo..maybe you have some insights. :)

**Comment by igalg99** [comment]
Omg! I am embarrassed to write this next sentence: 
The problem was discharged device (s) . NOT the integration.  It appears that all the 3 of  the  CubeTouch devices ran out of battery at the same time right after updating to HA 2023.11. talking about co-incidence. after charging the devices all works
