### ISSUE TITLE
Fingerbot (ltak7e1p) Not supported

### ISSUE THREAD

**Issue by Cres09** [PlusPlus-ua/ha_tuya_ble#9]
Integration doesn't create any switch or controls for my Fingerbot (ltak7e1p), only the signal strength sensor
![Captura](https://user-images.githubusercontent.com/118302081/235347922-f427e0a1-8c2d-4f4f-b89f-d212bfdb42fc.PNG)

Data points:
Switch:"2"
kanjis I can't copy:"130"
Click:"101"
Mode:"8"
Down movement:"9"
Sustain time:"10"
Invert:"11"
Battery level:"12"
Up movement:"15"
自定时编程:"111"
自定周编程1:"112"
Tap enable:"17"
自定周编程2:"113"
自定周编程3:"114"
自定周编程4:"115"
运动统计:"150"

Is this the info you need?

**Comment by PlusPlus-ua** [comment]
Yes, thank you.

Has your device button for manual control?

**Comment by Cres09** [comment]
Yes, it have.
![Captura](https://user-images.githubusercontent.com/118302081/235350083-2bd956c9-a319-4460-bc7b-0ca16456a3cd.PNG)

**Comment by Cres09** [comment]
Yes it have one.
![image0](https://user-images.githubusercontent.com/118302081/235350101-37a591b7-295c-4fb2-b283-538844b8914f.jpeg)

**Comment by PlusPlus-ua** [comment]
It looks like original Fingerbot, there is Fingerbot Plus with sensor button on the top:

![image](https://user-images.githubusercontent.com/26710811/235350223-51c046ae-e799-4a4a-8c69-65b9ce7cea46.png)

So, I'm going to add it.

**Comment by PlusPlus-ua** [comment]
Please check version 0.1.4

**Comment by Cres09** [comment]
Installed and tested. It returns an error:
![Captura](https://user-images.githubusercontent.com/118302081/235351867-b80e13fc-7509-4499-b0fd-b04d7a4f239f.PNG)

``Este error se originó a partir de una integración personalizada.

Logger: homeassistant
Source: custom_components/tuya_ble/cloud.py:182
Integration: Tuya BLE
First occurred: 13:58:03 (1 occurrences)
Last logged: 13:58:03

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 95, in _async_start
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 178, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 176, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 840, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 868, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/tuya_ble/config_flow.py", line 233, in async_step_bluetooth
    await self._manager.build_cache()
  File "/config/custom_components/tuya_ble/cloud.py", line 214, in build_cache
    await self._fill_cache_item(item)
  File "/config/custom_components/tuya_ble/cloud.py", line 182, in _fill_cache_item
    factory_info = fi_response[TUYA_RESPONSE_RESULT][0]
IndexError: list index out of range
`

Este error se originó a partir de una integración personalizada.

Logger: custom_components.tuya_ble.tuya_ble.tuya_ble
Source: custom_components/tuya_ble/tuya_ble/tuya_ble.py:525
Integration: Tuya BLE
First occurred: 13:59:04 (3 occurrences)
Last logged: 14:03:50

mac adress: Device unexpectedly disconnected; RSSI: None



Este error se originó a partir de una integración personalizada.

Logger: homeassistant.config_entries
Source: custom_components/tuya_ble/tuya_ble/tuya_ble.py:652
Integration: Tuya BLE
First occurred: 13:59:29 (3 occurrences)
Last logged: 14:04:12

Error setting up entry Fingerbot ACBCC5 for tuya_ble
Traceback (most recent call last):
  File "/config/custom_components/tuya_ble/tuya_ble/tuya_ble.py", line 640, in _ensure_connected
    if not await self._send_packet_while_connected(
  File "/config/custom_components/tuya_ble/tuya_ble/tuya_ble.py", line 893, in _send_packet_while_connected
    await asyncio.wait_for(future, RESPONSE_WAIT_TIMEOUT)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 432, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tuya_ble/__init__.py", line 44, in async_setup_entry
    await device.initialize()
  File "/config/custom_components/tuya_ble/tuya_ble/tuya_ble.py", line 272, in initialize
    await self.update()
  File "/config/custom_components/tuya_ble/tuya_ble/tuya_ble.py", line 312, in update
    await self._send_packet(TuyaBLECode.FUN_SENDER_DEVICE_STATUS, bytes())
  File "/config/custom_components/tuya_ble/tuya_ble/tuya_ble.py", line 843, in _send_packet
    await self._ensure_connected()
  File "/config/custom_components/tuya_ble/tuya_ble/tuya_ble.py", line 652, in _ensure_connected
    except [BLEAK_EXCEPTIONS, BleakNotFoundError]:
TypeError: catching classes that do not inherit from BaseException is not allowed

**Comment by aportillo365** [comment]
> Installed and tested. It returns an error: ![Captura](https://user-images.githubusercontent.com/118302081/235351867-b80e13fc-7509-4499-b0fd-b04d7a4f239f.PNG)
> 
> ``Este error se originó a partir de una integración personalizada.
> 
> Logger: homeassistant Source: custom_components/tuya_ble/cloud.py:182 Integration: Tuya BLE First occurred: 13:58:03 (1 occurrences) Last logged: 13:58:03
> 
> Error doing job: Task exception was never retrieved Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 95, in _async_start await gather_with_concurrency( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 178, in gather_with_concurrency return await gather( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 176, in sem_task return await task File "/usr/src/homeassistant/homeassistant/config_entries.py", line 840, in async_init flow, result = await task File "/usr/src/homeassistant/homeassistant/config_entries.py", line 868, in _async_init result = await self._async_handle_step(flow, flow.init_step, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step result: FlowResult = await getattr(flow, method)(user_input) File "/config/custom_components/tuya_ble/config_flow.py", line 233, in async_step_bluetooth await self._manager.build_cache() File "/config/custom_components/tuya_ble/cloud.py", line 214, in build_cache await self._fill_cache_item(item) File "/config/custom_components/tuya_ble/cloud.py", line 182, in _fill_cache_item factory_info = fi_response[TUYA_RESPONSE_RESULT][0] IndexError: list index out of range `
> 
> Este error se originó a partir de una integración personalizada.
> 
> Logger: custom_components.tuya_ble.tuya_ble.tuya_ble Source: custom_components/tuya_ble/tuya_ble/tuya_ble.py:525 Integration: Tuya BLE First occurred: 13:59:04 (3 occurrences) Last logged: 14:03:50
> 
> mac adress: Device unexpectedly disconnected; RSSI: None
> 
> Este error se originó a partir de una integración personalizada.
> 
> Logger: homeassistant.config_entries Source: custom_components/tuya_ble/tuya_ble/tuya_ble.py:652 Integration: Tuya BLE First occurred: 13:59:29 (3 occurrences) Last logged: 14:04:12
> 
> Error setting up entry Fingerbot ACBCC5 for tuya_ble Traceback (most recent call last): File "/config/custom_components/tuya_ble/tuya_ble/tuya_ble.py", line 640, in _ensure_connected if not await self._send_packet_while_connected( File "/config/custom_components/tuya_ble/tuya_ble/tuya_ble.py", line 893, in _send_packet_while_connected await asyncio.wait_for(future, RESPONSE_WAIT_TIMEOUT) File "/usr/local/lib/python3.10/asyncio/tasks.py", line 432, in wait_for await waiter asyncio.exceptions.CancelledError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/tuya_ble/**init**.py", line 44, in async_setup_entry await device.initialize() File "/config/custom_components/tuya_ble/tuya_ble/tuya_ble.py", line 272, in initialize await self.update() File "/config/custom_components/tuya_ble/tuya_ble/tuya_ble.py", line 312, in update await self._send_packet(TuyaBLECode.FUN_SENDER_DEVICE_STATUS, bytes()) File "/config/custom_components/tuya_ble/tuya_ble/tuya_ble.py", line 843, in _send_packet await self._ensure_connected() File "/config/custom_components/tuya_ble/tuya_ble/tuya_ble.py", line 652, in _ensure_connected except [BLEAK_EXCEPTIONS, BleakNotFoundError]: TypeError: catching classes that do not inherit from BaseException is not allowed

0.1.4 worked for me, and I have also a Fingerbot with "product_id": "ltak7e1p":
![1](https://user-images.githubusercontent.com/75343249/235359220-8d393985-5331-4f59-91ac-e9a65b996fa5.png)

![2](https://user-images.githubusercontent.com/75343249/235359233-4fca17f1-39e7-4afe-a2ce-23b32511323b.png)


Did you tried to unbind the device on SmartLife/Tuya App and bind again? After a reboot in Home assistant, that was the key step, before that I cannot add the device to the tuya_ble integration as well

Thanks again to the creators!!!

**Comment by Cres09** [comment]
That did the trick! Always forget to restart everything. Thank you very much. And many many thanks to the developer!
